mybatis-plus:
  type-aliases-package: com.july.**.entity
  type-enums-package: com.july.**.entity.enums
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
    type-aliases-super-type: com.july.company.entity.BaseEntity

#debug: true
#限制文件上传大小
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #是否开启跨域请求
  #cors:
  #   enabled: true
#logging:
#    config:
#    level:
#        com.alibaba.nacos : error